### ISSUE TITLE
Error in adding Nodon Octan to Homey... it will not pair

### ISSUE THREAD

**Issue by wurzel21** [caseda/com.nodon#1]
I have tried pairing the Nodon Actan with the homey ( 10.3 ) and I am not able to get this working.

I select the app and follow the instructions... it is hit or miss as to whether it it sees the device or not.

But on the small occasions it does...it goes from found node to "something went wrong".

i have reset both homey and the Nodon ... and still no Joy

**Comment by caseda** [comment]
what is the distance you are trying to add it to homey, can be a little bit finicky when the distance is too big

**Comment by wurzel21** [comment]
I am right next to the homey, and have tried it at various distances ( touching, 1 cm,5cm,10,cm, 50,cm 1 m, 2m, 3m) and all to no avail

**Comment by caseda** [comment]
I can still include my octan without any trouble, so its definitely not an app issue.

try rebooting your homey:
Homey's Settings -> System -> [Reboot homey]
make really sure the remote is reset manually
(holding the open circle and minus for 5 seconds until the led blinks red and green)

if that does not work, remove the power to homey for several minutes (10 atleast), then put in the power again

**Comment by caseda** [comment]
any news on this matter?

have you been able to including it to homey?

**Comment by wurzel21** [comment]
Hi,
I am still not able to add this device, I have reset, rebooted, updates homey to 0.10.7 and still get the same issue
when adding it says node found,

then Something went wrong 

I have deleted app, reinstalled, carried out from rough next to homey and at incremental distances. I have also changed the battery on the device.

not sure where to go now ??

**Comment by caseda** [comment]
if you have reset the remote manually, and it still doesn't work.

you might either have a:
broken/defective remote,
or
homey's z-wave chip is doing weird things,

do you have any other z-wave modules you can include?
if you can include them, then it _most likely_ is your remote that is broken/defective

**Comment by SergeRegoor** [comment]
My 2 cents: my Octan only paired after I did a factory reset. After that it paired successfully during the 2nd try.

**Comment by caseda** [comment]
No reaction from the OP anymore,
Going to close the issue as it seems solved now?

if not, don't be shy to re-open it again.
