### ISSUE TITLE
Nodon Smart Plug - Power failure notification

### ISSUE THREAD

**Issue by stephanetomas** [caseda/com.nodon#13]
Hello,

We have a problem with my nodon Smart Plug. Power failure notification not work. Could you please help me ?

Best Regards.

**Comment by stephanetomas** [comment]
![Screenshot_20190830-073039__01](https://user-images.githubusercontent.com/53584616/63995422-bcd0a000-caf8-11e9-95fc-2212d771be77.jpg)

**Comment by stephanetomas** [comment]
And sometimes application crash when i test power failure. I have create flow with notification when power failure but if not work.

**Comment by stephanetomas** [comment]
![Screenshot_20190830-073842__01](https://user-images.githubusercontent.com/53584616/63995577-54ce8980-caf9-11e9-9f5d-bb1eab652e5d.jpg)

**Comment by caseda** [comment]
😂 Somehow I really thought the setting and association was on by default, I guess not.
Thanks for reminding me! Now I can test it this evening too.

**Comment by stephanetomas** [comment]
I have test with default parameters and with différents parameters changed on "advanced settings / device specific - commands to association groups / power failure notification" and more but i have same problem.

**Comment by stephanetomas** [comment]
My application also continue to crash. I'm waiting update. Have you a delay for publication of update ? I think it must to be approved by Athom ?

**Comment by caseda** [comment]
Let me quote what I said yesterday.
> I will not send it to the app store yet as i also want to fix the icons of the devices, will do that tomorrow

**Comment by caseda** [comment]
> 😂 Somehow I really thought the setting and association was on by default, I guess not.
> Thanks for reminding me! Now I can test it this evening too.

Little more research, and it should be on by default 😛 my device just didn't receive the proper parameter value during pairing for some reason, now trying to fix it fully as my small fix didn't fix it yet.

**Comment by caseda** [comment]
i've got the triggers fully fixed now, just the icons left :)

**Comment by MarcoRits** [comment]
Great news!, need any help with the icons?

**Comment by caseda** [comment]
Already had them fixed, so no need, as indicated by the labels, the update is pending to be accepted into the app store by athom.

**Comment by caseda** [comment]
The update is now in the app store, let me know if this also fixes it for you
