### ISSUE TITLE
Nodon Smart Plug - Power was interupted or restored

### ISSUE THREAD

**Issue by stephanetomas** [caseda/com.nodon#15]
Hello,

We have two Nodon Smart Plug and I would like to monitor when power was interupted or restored with Homey Flow notification.

But IF condition with power was interupted or power was restored not work sistematicaly, sometimes it is necessary to remove and add the device again for it to work or to have to readjust the advanced parameters.

Could you please help me ?

Best Regards.

**Comment by caseda** [comment]
I'm completely reliant on the device if it sends the corresponding message that the power is gone or back again, if it doesn't send this, i can't do anything about that.
All I (the app) can do is listen to this message.

It can happen that the device is just _too far away_, so Homey just doesn't receive the message.
