### ISSUE TITLE
Add new remote dont work

### ISSUE THREAD

**Issue by MikNys** [caseda/com.nodon#17]
I tried to re-install my NodOn soft remote to Homey, but it doset work to add this device to Homey. 
It started with bad respons between Homey and the remote, so I remowed the remote from Homey and tried to connect them again. But it dosent work anymore. I have restared Homey, re-installed nodon app and also made a factory reset on the remote. No success of those attemts. So my guess is a software problem.

**Comment by caseda** [comment]
As you are the first one in a long time (at least 10 months, since the app was last updated), and over 800 active users, I _highly_ doubt it is a software/app problem.
It is more likely a battery that is (too) low, or the distance is too big, or a routing device in between that is acting up if it was routed before.

**Comment by MikNys** [comment]
Ok, maby I do something wrong but I am around 5cm from the Homey when I try to add the remote, battery indicator green on remote, also battery before I removed the remote from Homey was 100% according to Homey information. 
What else can I do?

**Comment by caseda** [comment]
As not being able to include a device isn't an app issue, i will close this issue.
Please replace your battery as even a green LED on the device itself doesn't necessarily mean the battery works properly enough for it to include, had the same myself not this week when one of my wall switches stopped working during rewrite to the new version, and really needed to replace the battery before it was able to re-include, and or work at all. (the led was still **green** when doing the battery check on the device itself)
