### ISSUE TITLE
Wake up interval for NodOn

### ISSUE THREAD

**Issue by da96blan** [caseda/com.nodon#18]
The NodOn wall switches are going into sleep mode and to avoid this I would like to use the wakeup function. The app v3.0.1 has a wakeup function but the interval can only be set to zero (0), which I guess effectively disables wakeup:
minimum value: 0
maximum value: 0
step value: 0

I would like to be able to configure a wakeup interval value higher than zero.

**Comment by caseda** [comment]
This is a device "limitation", the range is get from the remote (or any z-wave device for that matter) during pairing, NodOn only has a range from 0-0 (so always 0).
