### ISSUE TITLE
Softremote can't be found by homey after update's

### ISSUE THREAD

**Issue by Bakkerwj** [caseda/com.nodon#19]
Since one of the latest home'y update my softremote's 2x don't work anymore after a while and i have to ad the again. avocet every 24 hour's....

**Comment by caseda** [comment]
With this amount of information it is pretty much impossible to help you fully.
Not sure why an update of Homey makes it an app issue, cause it doesn't (have my wall switches working just fine on v6 for example).

But this more likely seems to be a battery (too) empty issue, NodOn devices like their batteries being full (+80%) when (trying) to pair, so have you tried replacing the batteries yet?
yes, even if the LED shows green, and the app shows a high(ish) percentage, that has the tendency of not being reliable.
