### ISSUE TITLE
Save settings button greyed out with NodOn Octan remote

### ISSUE THREAD

**Issue by SergeRegoor** [caseda/com.nodon#2]
Tried re-pairing the remote, and rebooted Homey multiple times. No error message in the Chrome dev console.

![2016-10-29 08_48_08-zones devices - homey](https://cloud.githubusercontent.com/assets/22777508/19827755/752ab390-9db4-11e6-827c-7503dc1821e9.png)

**Comment by caseda** [comment]
Seems like Wake-up interval isn't overwritten anymore in settings, filled in a generic issue about it
https://github.com/athombv/homey/issues/1153

Will leave it open until it really is fixed 👍

**Comment by caseda** [comment]
will be fixed in the next nodon update (1.0.3), it was a mistake on my part :blush:

app is now up for approval so shouldn't take too too long

**Comment by caseda** [comment]
now officially (fully) fixed in 1.1.0 update.

so closing this issue now 😄
