### ISSUE TITLE
How to add nodon wall switch

### ISSUE THREAD

**Issue by Ddddim** [caseda/com.nodon#21]
Hello, 
Il have a nodon Wall switch but when i try to add
Application say
 press 
Upper left and upper right 
Upper left 
But nothing happend ?
On manual of nodon it s written 3 time upper left but it doesnt work.
Sorry but could you please help me.

**Comment by caseda** [comment]
Are you sure it is the **z-wave** version? as all my manuals state the top 2 buttons, then the left top button.
This app doesn't support the zigbee nor the enOcean versions.

**Comment by caseda** [comment]
Bump

**Comment by Ddddim** [comment]
Hello,

I'm reallysorry for this delay. I know that is not serious. Please excuse me.Thank you for your first response. Thank you very much for sending me an email.I tried to find solutions on my own before bothering you again, but withoutsuccess.

I have : Homey pro (early 2019) v 8.1.0 who is nice working witharound 40 connected devices.

I have installed and already used for at least two remotecontrols, a NodOn - Soft Remote EnOcean CRC-3-6-0x and a Fibaro Z-Wave KeyFob

In Homey I have: NodOn v3.0.1 and Fibaro v3.4.3

Suddenlyone remote then the other stopped working. I couldn't get it to work again so Iremoved them from Homey from the app. 

I restartedHomey but I can't add them anymore. I've tried to factory reset both remotesbut they don't respond properly. And I can't add them to Homey anymore

 

             


                


 

I also havetrouble adding to Homey:

 - the NodOn "Wall Switch" Z-Wave+CWS-3-1-0. This device worked with my old Zwave system.

- TKB Home -Z-Wave Plus double relay wall switch, white (TZ57-ZW5)

I tried different techniques. Move the homey box, wait... I do not know what to do. I am lost

Thank youvery much for all your work and your precious help.


    On Monday, December 5, 2022 at 03:46:03 PM GMT+1, R Mengers ***@***.***> wrote:  
 
 


Bump

**Comment by caseda** [comment]
You say you've already used the "NodOn - Soft Remote EnOcean", but that is **impossible**, Homey does not have support for Enocean, that is why I asked if you were sure it was the Z-Wave version.

Sounding that you have difficulty adding multiple z-wave devices, try replacing your power supply, the original power supply that comes with Homey can cause some weird behaviour.
If that doesn't fix it you'll have to contact Athom, as the inclusion process isn't handeld by the app, but by the Z-wave core in Homey.
