### ISSUE TITLE
Support for Homey Pro 2023

### ISSUE THREAD

**Issue by ghost** [caseda/com.nodon#22]
Are you planning to make this app available for Homey 2023? I cannot find this app in the list of apps which are updated or planned for updating. 
I want to swich from Domoticz to Homey (2023) and I have about 5 Nodon switches. Unfortunately I am not able to program in Java. 
Already thanks for answering.

**Comment by caseda** [comment]
This app isn't in that list because support is already there for about 2 years now.

**Comment by ghost** [comment]
That’s great. Thanks for making this app and sorry that I bothered you.
