### ISSUE TITLE
Pairing Wall switch doesn’t work

### ISSUE THREAD

**Issue by JockeD** [caseda/com.nodon#24]
I have two NodOn Wall Switch, z-wave. Both have stopped working. Tried to remove and pair them again. But it’s impossible to pair them. Following the manual pressing both top left and top right until the led blinks pink then tapping the bottom left button. After that two short pink flashes and the nothing happens. I have tried this really many times, also really close to the homey, but without success.

**Comment by caseda** [comment]
Have you tried replacing the batteries?

**Comment by JockeD** [comment]
Replacing batteries didn’t help. Then tested to pair using the native z-wave pairing, which worked.
