### ISSUE TITLE
Parking smart plug don't work

### ISSUE THREAD

**Issue by Laurent41150** [caseda/com.nodon#25]
Hello. When I try parring smart plug or micro smart plug in Homey Pro 2023, I have a message "transmit_complete_noroute". Can you help me ?

**Comment by Laurent41150** [comment]
Résolve after restting homey pro

**Comment by caseda** [comment]
This is not an app issue but an issue of the Z-Wave core of Homey Pro 2023, please contact Athom so it gets higher on their priority list.
