### ISSUE TITLE
Wall Switch pair does not work with NoDon App

### ISSUE THREAD

**Issue by evxjson** [caseda/com.nodon#3]
Hi!
I have spent some time trying to get the Wall Switch to join the Z-Wave network. Most of the time it says that "something went wrong" but sometimes nothing happens at all. What I have tried:

- Reset my Z-Wave network back to default.
- Restart Homey. 
- Reset NodOn Wall Switch.
- Pulled out battery from NodOn Wall Switch.

At last I tried to add the device using "Homey" -> "Z-Wave" button (instead of NodOn -> "Wall Switch") and it work directly! Something seems to be wrong with the NodOn App for adding this device.

Homey firmware version: 1.5.3
NodOn version: 1.1.1
NodOn Wall Switch: CWS-3-1-01 (3700313920268)

/Anders Jansson

**Comment by caseda** [comment]
That is not possible and is just a coincidence that it didn't work with the app itself.

the inclusion is completely the same except for the learnmode not being shown at the start.
Inclusion is done by the homey core, only the last few steps are using information stored in the app,
but that is also the same for app vs generic inclusion.
